// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAemXNCREY_F0Ag9GZPJmk1y3evTEy2OCE',
    appId: '1:696036947396:web:4480a8a96360b33c582091',
    messagingSenderId: '696036947396',
    projectId: 'smartdoorbell-416b6',
    authDomain: 'smartdoorbell-416b6.firebaseapp.com',
    storageBucket: 'smartdoorbell-416b6.firebasestorage.app',
    measurementId: 'G-NRG8RVKXXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ3zcr4MLjs14nU_flUpVL905aQokgR1w',
    appId: '1:696036947396:android:4511e502b1ffe73e582091',
    messagingSenderId: '696036947396',
    projectId: 'smartdoorbell-416b6',
    storageBucket: 'smartdoorbell-416b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzxdLP95nfLfkYHs_VP3zO1C4bz57SZwo',
    appId: '1:696036947396:ios:3db10e7e6efd6a02582091',
    messagingSenderId: '696036947396',
    projectId: 'smartdoorbell-416b6',
    storageBucket: 'smartdoorbell-416b6.firebasestorage.app',
    iosBundleId: 'com.example.wirelessDoorbellApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzxdLP95nfLfkYHs_VP3zO1C4bz57SZwo',
    appId: '1:696036947396:ios:3db10e7e6efd6a02582091',
    messagingSenderId: '696036947396',
    projectId: 'smartdoorbell-416b6',
    storageBucket: 'smartdoorbell-416b6.firebasestorage.app',
    iosBundleId: 'com.example.wirelessDoorbellApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAemXNCREY_F0Ag9GZPJmk1y3evTEy2OCE',
    appId: '1:696036947396:web:4482db3df289fa2f582091',
    messagingSenderId: '696036947396',
    projectId: 'smartdoorbell-416b6',
    authDomain: 'smartdoorbell-416b6.firebaseapp.com',
    storageBucket: 'smartdoorbell-416b6.firebasestorage.app',
    measurementId: 'G-LWHMPD78TV',
  );
}
